version: "3.3"
services:
  grafana:
    image: tadbiri/grafana
    restart: always
    user: root
    ports:
      - 0.0.0.0:3001:3000
    volumes:
      - /cbshome/cdr_analysis/app/cdr_db_inserter/config/monitor/grafana/lib/:/var/lib/grafana/
      - /cbshome/cdr_analysis/app/cdr_db_inserter/config/monitor/grafana/etc/:/etc/grafana/
      - /cbshome/cdr_analysis/app/cdr_db_inserter/config/monitor/grafana/log/:/var/log/grafana/
  prometheus:
    image: tadbiri/prometheus
    network_mode: host
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /cbshome/cdr_analysis/app/cdr_db_inserter/config/monitor/prometheus/:/prometheus
  postgres-exporter:
    image: tadbiri/postgres-exporter
    network_mode: "host"
    user: root
    environment:
      DATA_SOURCE_NAME: "postgresql://root:1qaz@WSX@10.15.90.203:5432/postgres?sslmode=disable"
