global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    scrape_interval: 1m
    scrape_timeout: 30s
    static_configs:
      - targets: ["localhost:9187"]